version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: products
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456#
    ports:
      - "5432:5432"
    networks:
      - app-network

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    networks:
      - app-network
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - postgres

volumes:
  db:

networks:
  app-network:
    driver: bridge