spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/products
    username: root
    password: 123456#
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    baselineOnMigrate: true

server:
  port: 8080
  servlet:
    context-path: /api

